language: python

python:
- "3.6"

services:
- docker

cache: pip

before_install:
- export PYTHONPATH=$HOME/christopherjmedlin/vimcanvas

install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt

script: 
- py.test --cov=. tests/
- docker build -t quay.io/christopherjmedlin/vimcanvas:latest .

after_success: coveralls

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master