version: '2'

services:
  web:
    image: quay.io/christopherjmedlin/vimcanvas:latest
    env_file: .env
    command: python3.6 manage.py run
    volumes:
      - .:/opt/vimcanvas
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "443:443"
      - "80:80"