version: '2'

services:
  web:
    build: .
    command: python3.6 manage.py run
    volumes:
      - .:/opt/vimcanvas
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "443:443"
      - "80:80"